import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const supabase=createClient('https://otwnmfoubxdenqkrkxmx.supabase.co','sb_publishable_cEI9jtk6n0S01-2dGaPn3A_MLT28InS');
const $=(s)=>document.querySelector(s); let user=null,posts=[],activePost=null;
const notice=(m,e=false)=>{const n=$('#notice');n.hidden=false;n.textContent=m;n.style.background=e?'#fee4e2':'#edf3ef';setTimeout(()=>n.hidden=true,5000)};
async function session(){const {data}=await supabase.auth.getSession();user=data.session?.user||null;$('#member-state').textContent=user?'Member':'Guest';$('#auth-button').textContent=user?'アカウント':'ログイン';$('#sign-out').hidden=!user}
async function load(){let q=supabase.from('post_feed').select('*');const c=$('#category').value;if(c)q=q.eq('category',c);const {data,error}=await q;if(error){notice('Supabaseの初期設定が必要です。SQLを実行してください。',true);return}posts=data||[];render()}
function filtered(){const s=$('#search').value.toLowerCase();let a=posts.filter(p=>(p.title+' '+p.body+' '+(p.tags||[]).join(' ')).toLowerCase().includes(s));if($('#sort').value==='popular')a.sort((x,y)=>y.favorite_count-x.favorite_count);else a.sort((x,y)=>new Date(y.created_at)-new Date(x.created_at));return a}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){const a=filtered();$('#post-count').textContent=posts.length;$('#result-count').textContent=a.length+'件';$('#feed').innerHTML=a.length?a.map(p=>`<article class="post"><div class="post-top"><span>${esc(p.category)}</span><small>${esc(p.display_name)} · ${new Date(p.created_at).toLocaleDateString('ja-JP')}</small></div><h3>${esc(p.title)}</h3><p class="post-body">${esc(p.body)}</p><div>${(p.tags||[]).map(t=>`<span class="tag">#${esc(t)}</span>`).join('')}</div><div class="post-actions"><button data-fav="${p.id}">♡ ${p.favorite_count}</button><button data-comments="${p.id}">コメント ${p.comment_count}</button>${user?.id===p.user_id?`<button data-delete="${p.id}">削除</button>`:''}</div></article>`).join(''):'<p class="empty">まだ投稿がありません。最初の知恵を共有してみましょう。</p>'}
$('#auth-button').onclick=()=>$('#auth-dialog').showModal();$('#new-post').onclick=()=>user?$('#composer').hidden=false:$('#auth-dialog').showModal();$('#cancel-post').onclick=()=>$('#composer').hidden=true;
$('#send-magic').onclick=async()=>{const email=$('#email').value,name=$('#display-name').value;const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+'/app.html',data:{display_name:name}}});$('#auth-message').textContent=error?error.message:'メールを送りました。リンクを開いてください。'};
$('#sign-out').onclick=async()=>{await supabase.auth.signOut();location.reload()};
$('#post-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await supabase.from('posts').insert({user_id:user.id,title:f.get('title'),body:f.get('body'),category:f.get('category'),tags:String(f.get('tags')).split(/[,、]/).map(x=>x.trim()).filter(Boolean)});if(error)return notice(error.message,true);e.target.reset();$('#composer').hidden=true;notice('投稿しました');load()};
$('#feed').onclick=async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.fav){if(!user)return $('#auth-dialog').showModal();const {error}=await supabase.from('favorites').insert({user_id:user.id,post_id:b.dataset.fav});if(error?.code==='23505')await supabase.from('favorites').delete().eq('user_id',user.id).eq('post_id',b.dataset.fav);load()}if(b.dataset.delete&&confirm('削除しますか？')){await supabase.from('posts').delete().eq('id',b.dataset.delete);load()}if(b.dataset.comments)openComments(b.dataset.comments)};
async function openComments(id){activePost=id;const {data}=await supabase.from('comments').select('*,profiles(display_name)').eq('post_id',id).order('created_at');$('#comments-list').innerHTML=(data||[]).map(c=>`<div class="comment"><b>${esc(c.profiles?.display_name)}</b><p>${esc(c.body)}</p></div>`).join('')||'<p>コメントはまだありません。</p>';$('#comments-dialog').showModal()}
$('#comment-form').onsubmit=async e=>{e.preventDefault();if(!user)return $('#auth-dialog').showModal();const body=new FormData(e.target).get('body');const {error}=await supabase.from('comments').insert({post_id:activePost,user_id:user.id,body});if(error)return notice(error.message,true);e.target.reset();openComments(activePost);load()};
['search','category','sort'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',()=>id==='category'?load():render()));
await session();await load();supabase.auth.onAuthStateChange(async()=>{await session();render()});